"""
NFT Module for EchoWorld Nexus
Mobility Passport NFT minting on Polygon Amoy testnet
"""

import json
import os
from typing import Dict, Any, Optional
from datetime import datetime


POLYGON_AMOY_RPC = "https://rpc-amoy.polygon.technology"
POLYGON_AMOY_CHAIN_ID = 80002


def create_mobility_passport_metadata(
    user_id: str,
    country: str,
    city: str,
    success_probability: float,
    vtc_optimized: bool,
    approval_rate: float,
    projected_savings: float,
    best_path: str
) -> Dict[str, Any]:
    """
    Create metadata for Mobility Passport NFT
    
    Args:
        user_id: Anonymous user identifier
        country: Destination country
        city: Destination city
        success_probability: Financial success probability
        vtc_optimized: Whether VTC optimization was applied
        approval_rate: Transaction approval rate
        projected_savings: Projected 12-month savings
        best_path: Recommended financial path
        
    Returns:
        NFT metadata dictionary
    """
    
    if success_probability >= 0.85:
        tier = "Gold"
        tier_description = "Exceptional financial readiness"
    elif success_probability >= 0.70:
        tier = "Silver"
        tier_description = "Strong financial foundation"
    elif success_probability >= 0.50:
        tier = "Bronze"
        tier_description = "Developing financial readiness"
    else:
        tier = "Starter"
        tier_description = "Beginning your journey"
    
    metadata = {
        "name": f"EchoWorld Mobility Passport - {country}",
        "description": (
            f"This NFT certifies the holder's simulated financial readiness "
            f"for relocation to {city}, {country}. Generated by EchoWorld Nexus "
            f"Financial Guardian Simulator."
        ),
        "image": "ipfs://placeholder_mobility_passport_image",
        "external_url": "https://echoworld-nexus.replit.app",
        "attributes": [
            {
                "trait_type": "Destination Country",
                "value": country
            },
            {
                "trait_type": "Destination City",
                "value": city
            },
            {
                "trait_type": "Success Probability",
                "value": f"{success_probability * 100:.0f}%"
            },
            {
                "trait_type": "Readiness Tier",
                "value": tier
            },
            {
                "trait_type": "VTC Optimized",
                "value": "Yes" if vtc_optimized else "No"
            },
            {
                "trait_type": "Approval Rate",
                "value": f"{approval_rate:.0f}%"
            },
            {
                "trait_type": "Projected Annual Savings",
                "value": f"€{projected_savings:,.0f}"
            },
            {
                "trait_type": "Recommended Path",
                "value": best_path
            },
            {
                "display_type": "date",
                "trait_type": "Simulation Date",
                "value": int(datetime.now().timestamp())
            }
        ],
        "properties": {
            "tier": tier,
            "tier_description": tier_description,
            "simulation_version": "1.0.0",
            "disclaimer": (
                "This NFT represents simulated financial planning data. "
                "It does not constitute financial advice or guarantee outcomes."
            )
        }
    }
    
    return metadata


def prepare_mint_transaction(
    wallet_address: str,
    metadata: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Prepare NFT mint transaction data (for frontend to execute)
    
    Args:
        wallet_address: User's wallet address
        metadata: NFT metadata
        
    Returns:
        Transaction data for web3 execution
    """
    
    tx_data = {
        "to": wallet_address,
        "metadata": metadata,
        "chain": "polygon_amoy",
        "chainId": POLYGON_AMOY_CHAIN_ID,
        "rpc": POLYGON_AMOY_RPC,
        "metadata_json": json.dumps(metadata, indent=2),
        "instructions": {
            "step1": "Connect your Web3 wallet (MetaMask recommended)",
            "step2": "Switch to Polygon Amoy Testnet",
            "step3": "Get testnet MATIC from faucet: https://faucet.polygon.technology/",
            "step4": "Confirm the mint transaction",
            "step5": "View your NFT on OpenSea Testnet"
        },
        "faucet_url": "https://faucet.polygon.technology/",
        "opensea_testnet": "https://testnets.opensea.io/"
    }
    
    return tx_data


def get_nft_preview_card(metadata: Dict[str, Any]) -> Dict[str, str]:
    """Generate data for NFT preview card UI"""
    
    attributes = {attr["trait_type"]: attr["value"] for attr in metadata.get("attributes", [])}
    
    return {
        "title": metadata.get("name", "Mobility Passport"),
        "description": metadata.get("description", ""),
        "country": attributes.get("Destination Country", "Unknown"),
        "city": attributes.get("Destination City", "Unknown"),
        "tier": metadata.get("properties", {}).get("tier", "Starter"),
        "tier_description": metadata.get("properties", {}).get("tier_description", ""),
        "success_prob": attributes.get("Success Probability", "0%"),
        "vtc_optimized": attributes.get("VTC Optimized", "No"),
        "approval_rate": attributes.get("Approval Rate", "0%"),
        "savings": attributes.get("Projected Annual Savings", "€0"),
        "path": attributes.get("Recommended Path", "Unknown")
    }


def generate_shareable_link(metadata: Dict[str, Any]) -> str:
    """Generate a shareable link for the passport (mock for MVP)"""
    
    import hashlib
    
    data_string = json.dumps(metadata, sort_keys=True)
    hash_id = hashlib.sha256(data_string.encode()).hexdigest()[:12]
    
    return f"https://echoworld-nexus.replit.app/passport/{hash_id}"


def check_web3_availability() -> Dict[str, Any]:
    """Check if Web3 functionality is available"""
    
    try:
        from web3 import Web3
        
        w3 = Web3(Web3.HTTPProvider(POLYGON_AMOY_RPC))
        connected = w3.is_connected()
        
        return {
            "available": True,
            "connected": connected,
            "chain": "Polygon Amoy Testnet",
            "chain_id": POLYGON_AMOY_CHAIN_ID,
            "rpc": POLYGON_AMOY_RPC
        }
    except Exception as e:
        return {
            "available": False,
            "error": str(e),
            "message": "Web3 not available - NFT preview mode only"
        }


SIMPLE_NFT_ABI = [
    {
        "inputs": [
            {"name": "to", "type": "address"},
            {"name": "tokenURI", "type": "string"}
        ],
        "name": "mint",
        "outputs": [{"name": "", "type": "uint256"}],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [{"name": "tokenId", "type": "uint256"}],
        "name": "tokenURI",
        "outputs": [{"name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function"
    }
]
